### ISSUE TITLE
В scipy есть стандартная функция scipy.signal.convolve2d

### ISSUE THREAD

**Issue by avlechen** [Geniny/ABC#1]
Есть подозрение, что 4 вложенных цикла будут работать не так хорошо, как функция стандартной библиотеки. 
Измерь время работы своей функци свертки и библиотечной.

**Comment by Geniny** [comment]
Тоже сделал , во вторник покажу, ну оно и так понятно , что библиотечная функция быстрее будет , просто у меня смысл был в том чтоб реализовать эту свертку в курсовом

**Comment by Geniny** [comment]
Решено
